### ISSUE TITLE
add manifest.json support  (Suggestion)

### ISSUE THREAD

**Issue by Allen-B1** [peppermintos/ice#10]
There is somethong called the web app manofest which basically gives you slme information about the web app, such as name or description

**Comment by pshem** [comment]
The specification is at https://www.w3.org/TR/appmanifest/ 

ice would have to grab the page at the link, check if it contains <link rel="manifest" href="manifest.json">, parse it and populate the .desktop file with it

Do you know of any applications that actually use a manifest? That would be useful as an example for testing. Manifests currently aren't supported by any desktop browsers [https://developer.mozilla.org/en-US/docs/Web/Manifest#Browser_compatibility](url), and I've not found any in a preliminary search

**Comment by darthlukan** [comment]
If I understand the request correctly, your goal is that ICE would be able to read the manifest.json in order to populate a `app_name.desktop` file with the correct name of the application as opposed to requiring the user to do it via the interface.

Currently, few web sites and web apps make use of the manifest, so I'm not sure how convenient it would be on a large scale for users (sometimes adding a feature which works but is only invoked on a super small subset of things appears as a breakage as opposed to the content just not making use of the feature), but it's definitely something to talk about and consider.
