### ISSUE TITLE
Can't download icon from the internet

### ISSUE THREAD

**Issue by michaldybczak** [peppermintos/ice#22]
I want to add https://app.asana.com
When I click on "use icon from the site" and then apply, I get:

> Http or url error. The site is probably unavailable or closed.

The site works fine and I use: https://app.asana.com
So what is the issue? Why can't it download the icon? When I proceed anyway I get the usual ice-ssb icon and I know I can change the icon manually by downloading it and providing the path to it in .desktop file but I remember this was working fine in the past.

The problem exists independently on the browser I want to set and on the link so I can use https://app.asana.com/ instead and it's always the same problem. On other sites it works, so what is this about this specific one? It does have an icon.

If the issue happens on this site then most probably there will be other sites with this bug as well.

**Comment by rhein** [comment]
I took a look at this. The problem seems to me that https://app.asana.com returns a HTTP 400 error to the script, so it can not find out any icon-url to use. This is more a problem of this server, but it maybe also the app can change its call so there is no 400 error in the first place. If I get the time I'll take a closer look.

Workaround in such cases: first use a different URL to get the Icon (such as just asana.com) and then edit the URL again to whatever should be used in the app.

**Comment by michaldybczak** [comment]
Thanks, that is a good workaround.

What is the problem here? Is server blocking access to the icon if it's not shipped with the whole site? Can't the server be tricked into thinking it is showing the whole site and then ice-ssb would grab the only icon?

If that issue is very rare then I guess there is no need to change the program for it and it's better to your the workaround thou. If more sites do the same, then maybe some solution would be needed.

**Comment by rhein** [comment]
yes, already in. Just a simple fix of the User-Agent, to make it the current Firefox on Windows. For whatever reason asana decided to block the old agent ...

**Comment by michaldybczak** [comment]
Unfortunately, there is no ice-ssb-git package in AUR so I have to wait for the next release for it to test but it's goo to know that it's out of the way.
